name = "cf_ai_superbowl_chatbot"
main = "src/index.js"
compatibility_date = "2025-01-20"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CHAT_MEMORY"
class_name = "ChatMemory"

[[migrations]]
tag = "v1"
new_classes = ["ChatMemory"]
